#motors
LEFT_MOTOR_FORWARD_PIN   = 22
LEFT_MOTOR_BACKWARD_PIN  = 27
RIGHT_MOTOR_FORWARD_PIN  = 17
RIGHT_MOTOR_BACKWARD_PIN = 18
MAX_ACCEL = 1 #m/s^2

# dist sensor
ECHO_PIN = 23
TRIG_PIN = 24
MAX_DIST = 4 #m

#servo
SERVO_PIN = 12
SERVO_MIN_PULSE_WIDTH = 0.5/1000
SERVO_MAX_PULSE_WIDTH = 2.5/1000
SERVO_INIT_ANGLE=0
SERVO_MIN_ANGLE = -90
SERVO_MAX_ANGLE = 90
SERVO_FRAME_WIDTH = 20/1000